### ISSUE TITLE
Selecting an emoji does not call the onChange. As a result if the last input is an emoji it does not get set in the message.

### ISSUE THREAD

**Issue by abezafar** [cesarwbr/react-input-emoji#13]

**Comment by Ajprakash17** [comment]
me also getting this issue , we  temporarily fixed 


const target = document.querySelectorAll('.react-input-emoji--input')[0];
  const container = document.createElement('div')
  container.innerHTML = target.innerHTML
  const images = Array.prototype.slice.call(container.querySelectorAll('img'))

  images.forEach(image => {
    image.outerHTML = image.dataset.emoji
  })
  let text = container.innerText
  text = text.replace(/\n/ig, '')

 return text;

**Comment by Corlai** [comment]
Update to 3.1.0 is resolved!!
