### ISSUE TITLE
Input width increases as you type, overflow x not working properly

### ISSUE THREAD

**Issue by myufa** [cesarwbr/react-input-emoji#15]

**Comment by cesarwbr** [comment]
@myufa have you tried the last version?

**Comment by celebritydeveloper** [comment]
Latest version doesn't work.

**Comment by celebritydeveloper** [comment]
@myufa I found a hack for this. Wrap the `<InputEmoji />` in a `<div></div>` then give the div a width and max width of same value. This method will help contain the overflow of the Input. This works for me, do let me know if it works for you. I will be glad to put you through.
