### ISSUE TITLE
How can i set a default value in InputEmoji , it is always the value set as " " 

### ISSUE THREAD

**Issue by louayyahyaoui** [cesarwbr/react-input-emoji#19]
`<InputEmoji
                value={text}
                onChange={setText}
                cleanOnEnter
                placeholder="Votre commentaire ici ..."
                onEnter={handleUpdateComment}
              />`

the text variable contain a value for example "Hello there" but it didnt display in the input

**Comment by kamran08** [comment]
did you get any solutions @louayyahyaoui

**Comment by farhadhabibi** [comment]
@louayyahyaoui  bro, did you get this issue resolved, I am still having the same promlem.

**Comment by louayyahyaoui** [comment]
Sorry but i didnt get any solution yet

**Comment by farhadhabibi** [comment]
@PavelLazarchuk, thank you bro it helps me alot, could you please tell me why I should use 'useEffect' since I tried to make it without useEffect but it did not work?

**Comment by xNevrroXx** [comment]
Just use value from the useState hook and pass it to the value prop of the <InputEmoji/> component.
```typescript
const App = () => {
    const [message, setMessage] = useState<string>("default message");
    
    return (
        <InputEmoji value={message} />
    );
}
```
