### ISSUE TITLE
Could not find a declaration file for module 'react-input-emoji'

### ISSUE THREAD

**Issue by jeff-pal** [cesarwbr/react-input-emoji#20]
This lib does not support `tsx`? I'm trying to use this lib within a React app + Typescript (`.tsx`). But I'm getting the following error on `import`:

```
Could not find a declaration file for module 'react-input-emoji'
 | import InputEmoji from "react-input-emoji";
 |                         ^^^^^^^^^^^^^^^^^^
```

**Comment by fixent30** [comment]
> This lib does not support `tsx`? I'm trying to use this lib within a React app + Typescript (`.tsx`). But I'm getting the following error on `import`:
> 
> ```
> Could not find a declaration file for module 'react-input-emoji'
>  | import InputEmoji from "react-input-emoji";
>  |                         ^^^^^^^^^^^^^^^^^^
> ```

I'm also facing this issue , can you tell me if you solve this or not ?

**Comment by abhishekram404** [comment]
I am facing the same issue.

**Comment by dev-bre** [comment]
same here... is there any plan on adding propoer TS types?

**Comment by DocSJ1980** [comment]
Same issue here but without the use of typescript. How other people are able to use?

**Comment by cesarwbr** [comment]
Good news! I've recently added TypeScript support. Please ensure you have the latest version installed. If you've just updated, you might need to restart your TypeScript server (or your IDE) to pick up the new type definitions.

If you're still facing any issues after updating, please let me know. Thanks for using `react-input-emoji`!
