### ISSUE TITLE
Component is not customizeable.

### ISSUE THREAD

**Issue by celebritydeveloper** [cesarwbr/react-input-emoji#23]
Please can a style props be added to the `<InputEmoji />` component so we can easily customize the width and height the way we want?

**Comment by JeanOviedo** [comment]
Add your own styles in a css file, to give it your own styles
Example in my projetc

.emoji-mart-category-label span {
    background-color: #f5f5f5 !important;
    color: #222 !important;
}
.emoji-mart-dark .emoji-mart-search input {
    color: #222 !important;
    border-color: #c8c5c2 !important;
    background-color:  #eeece9 !important;
    
}
.emoji-mart-dark {
    color: #222 !important; 

}

**Comment by cesarwbr** [comment]
@celebritydeveloper In version 5.7.1, you can customize the appearance by setting the following properties:

background: Controls the background color
borderColor: Sets the color of the border
color: Specifies the text color
placeholderColor: Defines the color of the placeholder text

Adjust these properties to achieve the desired look and feel of the component.
