### ISSUE TITLE
Different positions for the emoji popover.

### ISSUE THREAD

**Issue by Twonarly1** [cesarwbr/react-input-emoji#24]
Would like to use in a project, but the popover is in the 'top' position, and it reads off the page. A 'bottom', 'right', 'left' position would be a great addition!

**Comment by JGMichelle** [comment]
Were you ever able to find a solution to the popover positioning issue?

**Comment by cesarwbr** [comment]
Thanks for your suggestion! I appreciate you bringing this to our attention.

To address the issue of the Emoji popover reading off the page when in the 'top' position, we have implemented a new feature that allows the popover to automatically adjust its position based on the available space. The popover can now dynamically switch between 'top', 'bottom', 'right', and 'left' positions to ensure optimal visibility and prevent content from being cut off.

Please let us know if you have any further questions or feedback.

Thanks
