### ISSUE TITLE
Bug with emojis and whitespaces

### ISSUE THREAD

**Issue by etchebarneluis** [cesarwbr/react-input-emoji#26]
I'm facing a problem with emojis and whitespaces. For example, if you type an emoji and whitespace the placeholder doesn't disappear. Check the image below extracted from your official page.

<img width="960" alt="bug" src="https://user-images.githubusercontent.com/26497067/184236656-da767097-83d2-42fd-a424-cce8484a1fcc.png">
.

**Comment by etchebarneluis** [comment]
A faster fix is to conditional the place holder attribute -> placeholder={message.length === 0 ? "placeholder here..." : null}

**Comment by cesarwbr** [comment]
The issue related to placeholder and whitespaces has been resolved in the latest update. Please ensure you've updated and let me know if you face any further problems.
