### ISSUE TITLE
Issue in onchange

### ISSUE THREAD

**Issue by sathish-programmer** [cesarwbr/react-input-emoji#31]
i tried to use multiple function in onchage but it not working, how to trigger multiple function in onchange

**Comment by cesarwbr** [comment]
Hi @sathish-programmer!
In response to your issue about triggering multiple functions in the onchange event, you can indeed call multiple functions within a single handler. Here's a brief example:

```javascript
function handleOnChange() {
    firstFunction();
    secondFunction();
    // ... any other functions you want to call
}
```
If you're still facing issues, please share the relevant code snippets for further assistance.
