### ISSUE TITLE
Emoji picker gets crop when the input box is on top.

### ISSUE THREAD

**Issue by sawyen92** [cesarwbr/react-input-emoji#36]
If you see the attached picture, when the input box is on the top, the emoji picker does not adjust itself and gets cropped.

![image](https://user-images.githubusercontent.com/90792597/235407567-2ce3a5ad-f802-40b6-8ea7-3a0bf7702da3.png)

**Comment by KiranMungekar** [comment]
Hey, i did a css change as temporary solution. Hope this will help.
![image](https://github.com/cesarwbr/react-input-emoji/assets/35713742/0eaaee61-a6ac-436c-921a-fb069c269b6a)
![image](https://github.com/cesarwbr/react-input-emoji/assets/35713742/765597e1-3b7c-498f-b419-7c1cd4f42d14)

**Comment by cesarwbr** [comment]
fixed on version `5.2.1`
