### ISSUE TITLE
How to display in color emoji from input field to get response data?

### ISSUE THREAD

**Issue by banandam** [cesarwbr/react-input-emoji#7]
How to display in color emoji from input field to get response data?

**Comment by cesarwbr** [comment]
Could you please clarify?

**Comment by SamsonEmelyanov** [comment]
+1. For example, if I use it in chat, how to make it in color? Picture with issue in the link (https://disk.yandex.ru/i/1Xo9Uy8VuFdopg).

**Comment by vinayaks0031** [comment]
how can we change the color of the input box I want to make it transparent.

**Comment by cesarwbr** [comment]
> how can we change the color of this InputEmoji box I want to make it transparent. Currently using Tailwind CSS but it's not working

In version `5.7.1`, you can customize the appearance by setting the following properties:

- `background`: Controls the background color
- `borderColor`: Sets the color of the border
- `color`: Specifies the text color
- `placeholderColor`: Defines the color of the placeholder text

Adjust these properties to achieve the desired look and feel of the component.

**Comment by cesarwbr** [comment]
Since `v5.8.0`, set `shouldConvertEmojiToImage` to `true` to convert emojis to `<img>` tags.
